### ISSUE TITLE
App crashes on dock/undock

### ISSUE THREAD

**Issue by evelikov** [crackededed/Xtra#47]
Above all - thanks for the neat app.

Been using the app for a little while now and every time I dock/undock the application seems to crash.
Device in question is Sony Xperia Z2 tablet, running CarbonROM/Android 8.1.0.

Happy to provide logs and test potential fixes :-)

**Comment by crackededed** [comment]
yeah i have no idea how to fix this. i don't actually know like the basics of android and fragments and stuff so there's not even any potential fixes i could do. so that's great. also on release build it crashes on like every screen except settings but on debug it only crashes on following screen. i'll leave this log here.
```
2022-03-28 02:13:59.246 30659-30659/com.github.andreyasadchy.xtra.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.andreyasadchy.xtra.debug, PID: 30659
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.andreyasadchy.xtra.debug/com.github.andreyasadchy.xtra.ui.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.github.andreyasadchy.xtra.ui.follow.FollowMediaFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5582)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5490)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.github.andreyasadchy.xtra.ui.follow.FollowMediaFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:630)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448)
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410)
        at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584)
        at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
        at androidx.fragment.app.FragmentActivity.lambda$init$1$androidx-fragment-app-FragmentActivity(FragmentActivity.java:128)
        at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(Unknown Source:2)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:313)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
        at com.github.andreyasadchy.xtra.ui.main.MainActivity.onCreate(MainActivity.kt:93)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5582) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5490) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7860) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
     Caused by: java.lang.NoSuchMethodException: com.github.andreyasadchy.xtra.ui.follow.FollowMediaFragment.<init> []
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:615)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:448) 
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
        at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2410) 
        at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2584) 
        at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116) 
        at androidx.fragment.app.FragmentActivity.lambda$init$1$androidx-fragment-app-FragmentActivity(FragmentActivity.java:128) 
        at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(Unknown Source:2) 
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:313) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249) 
        at com.github.andreyasadchy.xtra.ui.main.MainActivity.onCreate(MainActivity.kt:93) 
        at android.app.Activity.performCreate(Activity.java:7955) 
        at android.app.Activity.performCreate(Activity.java:7944) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5582) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5490) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7860) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by evelikov** [comment]
The official documentation on the topic seem rather limited as well - https://developer.android.com/training/monitoring-device-state/docking-monitoring

**Comment by NyanGuyMF** [comment]
Looks like stacktrace tells that it's required to have a no arguments constructor in `FollowMediaFragment` class:
`Caused by: java.lang.NoSuchMethodException: com.github.andreyasadchy.xtra.ui.follow.FollowMediaFragment.<init> []`
https://github.com/crackededed/Xtra/blob/b42cb51a91221255f2855801e6d577f069471dad/app/src/main/java/com/github/andreyasadchy/xtra/ui/follow/FollowMediaFragment.kt#L12

It actually says [here](https://developer.android.com/reference/android/app/Fragment.html#Fragment%28%29) that `Fragmets` require a no arguments constructor. It seems like they use `#newInstance()` methods to instantiate a `Fragment` activities.

I'm not an Android and Kotlin dev., so bear with me if something I said doesn't make sense ':)
