### ISSUE TITLE
App crashes when switching to followed channels or downloads

### ISSUE THREAD

**Issue by remixer-dec** [crackededed/Xtra#506]
v2.32.2

<pre>
android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: videos1.downloadChat (code 1299 SQLITE_CONSTRAINT_NOTNULL)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1920)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1841)
	at T1.c.A(SourceFile:8)
	at d6.m.t(SourceFile:7)
	at I3.c.a(SourceFile:112)
	at C1.m.k(SourceFile:164)
	at T1.g.onUpgrade(SourceFile:15)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at T1.g.i(SourceFile:5)
	at T1.g.z(SourceFile:64)
	at T1.g.a(SourceFile:24)
	at T1.h.r0(SourceFile:10)
	at M1.s.b(SourceFile:5)
	at h4.b1.s(SourceFile:29)
	at v6.a.h(SourceFile:9)
	at M6.L.run(SourceFile:97)
	at S5.r.run(SourceFile:802)
	at T6.j.run(SourceFile:3)
	at T6.a.run(SourceFile:96)
</pre>

Followed streams are also not displayed, just an empty tab (without an account). 
Updated from 2.28.0, rolled back for now.

**Comment by BrilliantlyEducated** [comment]
that's true, but for me i put the default following tab as channels, now every time i open the app it crashes immediately, please fix it

**Comment by crackededed** [comment]
i think this should be fixed now

**Comment by remixer-dec** [comment]
v2.32.3 is working as expected, thanks for a quick fix

**Comment by BrilliantlyEducated** [comment]
> i think this should be fixed now

i can confirm that you fixed it, now the app it doesn't crash like before, thank you

**Comment by gvdvg** [comment]
this happened to me after updating today, how long until the fix is pushed to droidify ?
If I uninstall and install an older version, would I lose all my local follows or should I wait ?
thanks
